language: csharp
solution: CSF.DecoratorBuilder.sln

jobs:
    include:
        -   dotnet: 3.1.101
            mono: none

script:
    -   dotnet build
    -   dotnet test -c Autofac_62
    -   dotnet test -c Autofac_51
    -   dotnet test -c Autofac_50
    -   dotnet test -c Autofac_49
    -   dotnet test -c Autofac_40
